### ISSUE TITLE
Improve readme.md

### ISSUE THREAD

**Issue by fabianmolinab** [adigitoleo/vim-mellow#10]
The readme requires installation and configuration information without having to install the theme. 
You can take as an example other topics that contain all the information and guides directly in the readme.
I really liked the theme in light mode...

**Comment by adigitoleo** [comment]
Thanks for the feedback!

> The readme requires installation and configuration information

There are very many plugin managers for vim/neovim, and they change quite often. I'd rather not have stale or misleading installation instructions. I have a note about which folders need to be copied into the runtime path:

> Otherwise, please add at least the `autoload`, `colors` and `doc` folders to your (Neo)Vim package/runtime path.

I will update this to mention `:h 'runtimepath'` as the place to read about the install location, and to mention the URL to the Github releases (tagged archives). Do you think that would be sufficient, or do you have a suggestion for what kind of information you felt was needed?

I can also mention `:colorscheme mellow` as the command to apply the theme, however, the configuration options are documented in `:h mellow`. Even though there are only 3 of them currently, I'd rather not maintain duplicate information. If you had an issue with any of the default configuration, please let me know.

> all the information and guides directly in the readme

It's a preference, I guess, but to my taste, a README file is a developer-facing document (building, testing & contribution instructions), not a user-facing document (installation, usage & configuration options). While many Github projects put entire documentation in the README, I don't agree with this approach. It bloats the repository and is inferior to other documentation formats like simple websites or wikis. I've often seen outdated information in these long README files.

I suggest using the Github wiki feature instead, or generated web documentation for larger things. In this case, though, there are only 3 options and I'm not sure it is justified. However, if you were confused by some options, let me know.

> I really liked the theme in light mode...

Thanks! If there is anything you like to see improved in dark mode, or statusline integrations, I'm willing to review PRs (probably not before next weekend).

**Comment by adigitoleo** [comment]
I hope your concerns are covered by 36255db, feel free to open new issues.
