### ISSUE TITLE
Add Lightline support

### ISSUE THREAD

**Issue by adigitoleo** [adigitoleo/vim-mellow#6]
There has been some interest in support for [airline](https://github.com/vim-airline/vim-airline) and [lightline](https://github.com/itchyny/lightline.vim), e.g. https://www.reddit.com/r/vim/comments/itqhs9/mellow_a_bglight_theme_and_statusline_combo/gav0m9h?utm_source=share&utm_medium=web2x&context=3.

They are quite popular plugins and it would be nice to support them. This issue is open for discussion about how to do it. I think it could be part of this plugin rather than pushed to the airline/lightline repos, since that might be easier to maintain.

It will be worth checking how others have done this, e.g.:
- [dracula](https://github.com/dracula/vim/blob/master/autoload/airline/themes/dracula.vim)
- [gruvbox](https://github.com/morhetz/gruvbox/blob/master/autoload/airline/themes/gruvbox.vim)

Other examples/templates welcome.

**Comment by heyitscassio** [comment]
I could be done how [selenized](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/selenized_light.vim) does, it is simpler, but i think there would not be compatible with `notermguicolors`. 

Or `airline#themes#get_highlight` can be used to get the User values in the airline theme, as you suggested in the reddit comment, so if you update the main theme, it's not needed to update the airline theme.
>  think it could be part of this plugin rather than pushed to the airline/lightline repos, since that might be easier to maintain.

Yes, i think now they are not taking new themes, after they developed a way for getting themes from other repos.

I'm trying to come up with a lightline theme based on your statusline.

**Comment by heyitscassio** [comment]
I made a prototype for the lightline light theme, what do you think? I based the colors from the mellow statusbar.
![insert](https://user-images.githubusercontent.com/14265358/97914426-9e82b780-1d2e-11eb-84a9-16c09f5bc81d.png)
![normal](https://user-images.githubusercontent.com/14265358/97914430-a0e51180-1d2e-11eb-9d1a-3a6c65d51837.png)
![visual](https://user-images.githubusercontent.com/14265358/97914437-a5112f00-1d2e-11eb-84dd-d0058981569c.png)

**Comment by adigitoleo** [comment]
> I could be done how [selenized](https://github.com/itchyny/lightline.vim/blob/master/autoload/lightline/colorscheme/selenized_light.vim) does, it is simpler, but i think there would not be compatible with `notermguicolors`.

Indeed it looks simpler, and I'm not too concerned with supporting `notermguicolors`. Even the main themes only have rudimentary support for it.

> Or `airline#themes#get_highlight` can be used to get the User values in the airline theme, as you suggested in the reddit comment, so if you update the main theme, it's not needed to update the airline theme.

Nice, that sounds like a good way to handle colors. I'm not super comitted to the current `User` colors so let me know if you think they need changes to support this. From the screenshots it looks good to me, but I'm not sure of how many colors lightline/airline needs.

**Comment by heyitscassio** [comment]
With the lightline theme i just made variables with the 15 terminal colors, i didn't find a way to import those directly from a highlight group or from the theme by itself, so if any colors are updated, the lightline theme has to be updated to. And for the airline theme, i'm not too familiar on how the theme works.

Tomorrow or later i can try making the dark variant. It would be helpful if you can post screenshots of the dark mellow statusbar for reference.

**Comment by adigitoleo** [comment]
I uploaded some screenshots (https://github.com/adigitoleo/vim-mellow-statusline/commit/135095db95b0e748beb1ff1469e0f6ab7ebc245d)

**Comment by adigitoleo** [comment]
> i didn't find a way to import those directly from a highlight group or from the theme by itself

I think I had the same trouble when looking at this before. Eventually I might refactor to set up the palette in an autoload function, so it can be used by any other plugins.

> And for the airline theme, i'm not too familiar on how the theme works

No worries, I preferred lightline as well (and might switch back after this PR if I find mellow-statusline too minimal).

**Comment by heyitscassio** [comment]
This is the dark lightline theme, what do you think?

Normal Mode:
![normal](https://user-images.githubusercontent.com/14265358/98020426-c4b55f80-1de1-11eb-9c29-7349d36a0b14.png)
Replace Mode:
![replace](https://user-images.githubusercontent.com/14265358/98020455-ce3ec780-1de1-11eb-8e8e-1c9130bc96ae.png)
Insert Mode:
![insert](https://user-images.githubusercontent.com/14265358/98020478-d565d580-1de1-11eb-9cd8-92fc42c33f9e.png)
Visual Mode:
![visual](https://user-images.githubusercontent.com/14265358/98020515-dbf44d00-1de1-11eb-97b5-66dd76418400.png)

I don't know if i like the color of the block with the percentage, but let me know what you think.

And another thing, it would be better to have two themes (mellow_dark and mellow_light) or choose them automatically based on the background?

**Comment by adigitoleo** [comment]
> I don't know if i like the color of the block with the percentage, but let me know what you think.

I see what you mean, it's too close to the backgound color right? It seems that `s:blue` is only being used for the tabline (`TabSel`) in those themes, maybe it can also be used for the percentage block?

> And another thing, it would be better to have two themes (mellow_dark and mellow_light) or choose them automatically based on the background?

I guess that is what `lightline#colorscheme#background()` is doing, right? I think it makes sense to choose it automatically based on `set bg` since the main theme also does this.

Thanks for working on this!

**Comment by heyitscassio** [comment]
I think using s:blue looks better
![2020-11-03-232646_735x740_scrot](https://user-images.githubusercontent.com/14265358/98062114-1e427c00-1e2c-11eb-8569-10524eb4be4c.png)

> I guess that is what lightline#colorscheme#background() is doing, right?

Exactly.

Later it would be possible to shave off some variables, if it was possible to extract the colors directly from a highlight group or a list. The [gruvbox](https://github.com/morhetz/gruvbox/blob/master/autoload/lightline/colorscheme/gruvbox.vim) theme does something like that.

**Comment by adigitoleo** [comment]
Hey, sorry I squashed those commits and merged before you could change to blue color, my bad. I'm still learning the whole git/GitHub thing. I've patched this in for v1.2.1 however.

**Comment by heyitscassio** [comment]
Oh sorry about that, i forgot to push the commit. That was my bad. But either way it worked out!

**Comment by adigitoleo** [comment]
Let me know if there is anything else you wanted to change. Until I find my old lightline setup I'm sticking to mellow-statusline, so that's why I didn't notice this right away :)
